#####################################################################################
# This Makefile Explains the fork implementation where it generates a child process
# In this program parent executes its PID with Calender of the month which is running
# and child execute the current Date.
######################################################################################

frkout:frk.o
	cc -o frkout frk.c

frk.o:frk.c

clean:
	rm -rf *.o frkout

